# Generated by Django 6.0.5 on 2026-05-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('hostel', 'Hostel'), ('pg', 'PG'), ('room', 'Room'), ('flat', 'Flat')], max_length=20, null=True),
        ),
    ]
